/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex1.java.forms;
import ex1.java.bbdd.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Víctor & Maribel
 */
public class frmEquips extends javax.swing.JFrame {

    /**
     * Creates new form frmEquips
     */
    public frmEquips(){
        initComponents();
        
        try {
            //Instanciació de equips.
            eq = new Equips();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnPrimer = new java.awt.Button();
        btnAnterior = new java.awt.Button();
        btnSeguent = new java.awt.Button();
        btnUltim = new java.awt.Button();
        btnSortir = new java.awt.Button();
        java.awt.Label lblIdEquip = new java.awt.Label();
        lblNomEquip = new java.awt.Label();
        lblEstadi = new java.awt.Label();
        lblPoblacio = new java.awt.Label();
        lblCodiPostal = new java.awt.Label();
        txtIdEquip = new java.awt.TextField();
        txtNomEquip = new java.awt.TextField();
        txtEstadi = new java.awt.TextField();
        txtPoblacio = new java.awt.TextField();
        txtCodPostal = new java.awt.TextField();
        btnAfegir = new java.awt.Button();
        btnEliminar = new java.awt.Button();
        btnNetejar = new java.awt.Button();
        txtResultat = new java.awt.TextField();
        lblCodiPostal1 = new java.awt.Label();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(433, 335));
        setResizable(false);

        btnPrimer.setActionCommand("primer");
        btnPrimer.setLabel("<<");
        btnPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerActionPerformed(evt);
            }
        });

        btnAnterior.setActionCommand("anterior");
        btnAnterior.setLabel("<");
        btnAnterior.setName(""); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSeguent.setActionCommand("seguent");
        btnSeguent.setLabel(">");
        btnSeguent.setName(""); // NOI18N
        btnSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguentActionPerformed(evt);
            }
        });

        btnUltim.setActionCommand("ultim");
        btnUltim.setLabel(">>");
        btnUltim.setName(""); // NOI18N
        btnUltim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimActionPerformed(evt);
            }
        });

        btnSortir.setLabel("Sortir");
        btnSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortirActionPerformed(evt);
            }
        });

        lblIdEquip.setName(""); // NOI18N
        lblIdEquip.setText("Id Equip");

        lblNomEquip.setName(""); // NOI18N
        lblNomEquip.setText("Nom Equip");

        lblEstadi.setName(""); // NOI18N
        lblEstadi.setText("Estadi");

        lblPoblacio.setName(""); // NOI18N
        lblPoblacio.setText("Població");

        lblCodiPostal.setName(""); // NOI18N
        lblCodiPostal.setText("Codi Postal");

        txtIdEquip.setEditable(false);
        txtIdEquip.setEnabled(false);
        txtIdEquip.setName(""); // NOI18N

        txtNomEquip.setName(""); // NOI18N

        txtEstadi.setName(""); // NOI18N

        txtPoblacio.setName(""); // NOI18N

        txtCodPostal.setName(""); // NOI18N

        btnAfegir.setActionCommand("afegir");
        btnAfegir.setEnabled(false);
        btnAfegir.setLabel("+");
        btnAfegir.setName(""); // NOI18N
        btnAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirPerformed(evt);
            }
        });

        btnEliminar.setActionCommand("eliminar");
        btnEliminar.setLabel("-");
        btnEliminar.setName(""); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEliminarPerformed(evt);
            }
        });

        btnNetejar.setActionCommand("netejar");
        btnNetejar.setLabel("o");
        btnNetejar.setName(""); // NOI18N
        btnNetejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetejarbtnAfegirPerformed(evt);
            }
        });

        txtResultat.setEditable(false);
        txtResultat.setEnabled(false);
        txtResultat.setName(""); // NOI18N

        lblCodiPostal1.setName(""); // NOI18N
        lblCodiPostal1.setText("Resultat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnPrimer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnNetejar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAfegir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSeguent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnUltim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSortir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodiPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodiPostal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomEquip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEquip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoblacio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodPostal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoblacio, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodiPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodiPostal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeguent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUltim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAfegir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNetejar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        btnPrimer.getAccessibleContext().setAccessibleName("primer");
        btnAnterior.getAccessibleContext().setAccessibleName("anterior");
        btnSeguent.getAccessibleContext().setAccessibleName("seguent");
        btnUltim.getAccessibleContext().setAccessibleName("ultim");
        lblCodiPostal1.getAccessibleContext().setAccessibleName("Resultat");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Captura de l'event clic del botó Sortir.
 * Tanca el formulari i l'aplicació
 * @param evt 
 */
    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortirActionPerformed
        // Per tal de tancar el formulari l'hem d'amagar (setVisible(false)) i matar-lo
        // (dispose)
    
        setVisible(false);
        dispose();
    
        // Per últim matem l'aplicació. 
        System.exit(0); 
    }//GEN-LAST:event_btnSortirActionPerformed
/**
 * Captura de l'event clic del botó Primer.
 * Mostra el primer registre de la taula Equips
 * @param evt 
 */
    private void btnPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerActionPerformed
        try {
            // TODO add your handling code here:
            Primer();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrimerActionPerformed
/**
 * Captura de l'event clic del botó Anterior.
 * Mostra el registre anterior a l'actual de la taula Equips
 * @param evt 
 */
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            // TODO add your handling code here:
            Anterior();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed
/**
 * Captura de l'event clic del botó Següent.
 * Mostra el registre següent a l'actual de la taula Equips
 * @param evt 
 */
    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguentActionPerformed
        try {
            // TODO add your handling code here:
            Seguent();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSeguentActionPerformed
/**
 * Captura de l'event clic del botó Últim.
 * Mostra el darrer registre de la taula Equips
 * @param evt 
 */
    private void btnUltimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimActionPerformed
        try {
            // TODO add your handling code here:
            Ultim();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUltimActionPerformed

    private void btnAfegirPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirPerformed
        try {
            // TODO add your handling code here:
            Afegir();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAfegirPerformed

    private void btnEliminarEliminarPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEliminarPerformed
        try {
            // TODO add your handling code here:
            Eliminar();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarEliminarPerformed

    private void btnNetejarbtnAfegirPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetejarbtnAfegirPerformed
        try {
            // TODO add your handling code here:
            Netejar();
        } catch (SQLException ex) {
            Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNetejarbtnAfegirPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmEquips frm = new frmEquips();
                frm.setVisible(true);
                try {
                    //Executa primer per posicionar-nos al primer element.
                    frm.Primer();
                } catch (SQLException ex) {
                    Logger.getLogger(frmEquips.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAfegir;
    private java.awt.Button btnAnterior;
    private java.awt.Button btnEliminar;
    private java.awt.Button btnNetejar;
    private java.awt.Button btnPrimer;
    private java.awt.Button btnSeguent;
    private java.awt.Button btnSortir;
    private java.awt.Button btnUltim;
    private javax.swing.JButton jButton1;
    private java.awt.Label lblCodiPostal;
    private java.awt.Label lblCodiPostal1;
    private java.awt.Label lblEstadi;
    private java.awt.Label lblNomEquip;
    private java.awt.Label lblPoblacio;
    private java.awt.TextField txtCodPostal;
    private java.awt.TextField txtEstadi;
    private java.awt.TextField txtIdEquip;
    private java.awt.TextField txtNomEquip;
    private java.awt.TextField txtPoblacio;
    private java.awt.TextField txtResultat;
    // End of variables declaration//GEN-END:variables
    
    //Declaració de equips.
    private Equips eq;  
    /**
     * Mostra el primer registre de la taula Equips
     */
    private void Primer() throws SQLException{
        /*Insereix aquí el codi per mostrar el primer registre,
        Ha de fer la crida a primer, i passar l'objecte Equip que
        retorna aquest mètode a la funció mostrarEquip(eq)*/
        Equip equip=eq.primer();
        mostrarEquip(equip);
        actualitzarBotons(false, true);

    }

     /**
     * Mostra el registre anterior
     */
    private void Anterior() throws SQLException{
        /*Insereix aquí el codi per mostrar el primer registre*/
        this.Actualitzar();
        Equip equip=eq.anterior();
        mostrarEquip(equip);
        
        if(eq.esPrimer()){
            actualitzarBotons(false, true);
        }else{
            actualitzarBotons(true, true);
        }
    }

     /**
     * Mostra el registre següent
     */
    private void Seguent() throws SQLException{
        /*Insereix aquí el codi per mostrar el primer registre*/
        this.Actualitzar();
        Equip equip=eq.seguent();
        mostrarEquip(equip);
        
        if(eq.esUltim()){
            actualitzarBotons(true, false);
        }else{
            actualitzarBotons(true, true);
        }
    }
     /**
     * Mostra el darrer registre
     */
    private void Ultim() throws SQLException{
        /*Insereix aquí el codi per mostrar el primer registre*/
        Equip equip=eq.ultim();
        mostrarEquip(equip);
        actualitzarBotons(true, false);
    }
    //Afegeix un registre recuperat del formulari.
    private void Afegir() throws SQLException{
        Equip equip = recuperarEquip();
        
        if(equip!=null){
            eq.afegirEquip(equip);
            txtResultat.setText("INSERCIÓ CORRECTE");
            btnEliminar.setEnabled(true);
            btnAfegir.setEnabled(false);
            eq.refrescar();
            this.Ultim();
        } 
    }
    //Eliminació del element actual i ens porta al primer si es correcte. Amb dialeg incuit.
    private void Eliminar() throws SQLException{
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Vols eliminar aquest registre?","Alerta",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            if(eq.eliminarEquip()){
                txtResultat.setText("ELIMINACIÓ CORRECTE");
                eq.refrescar();
                this.Primer();
            } else {
                txtResultat.setText("ELIMINACIÓ INCORRECTE");
            }
        } else {
            txtResultat.setText("ELIMINACIÓ CANCELADA");
        }
        
    }
    //Neteja el formulari i desactiva els botons de navegació.
    private void Netejar() throws SQLException{
        actualitzarBotons(false, false);
        txtCodPostal.setText("");
        txtEstadi.setText("");
        txtIdEquip.setText("");
        txtNomEquip.setText("");
        txtPoblacio.setText("");
        btnEliminar.setEnabled(false);
        btnAfegir.setEnabled(true);
    }
    //Funció que actualitza els registres de la base de dades si son diferents.
    private void Actualitzar() throws SQLException{
        Equip eq1 = eq.actual();
        Equip eq2 = this.recuperarEquip();
        

        if(eq1.comparador(eq2)){
            txtResultat.setText("IGUALS");
        } else {
            eq.actualitzarEquip(eq2);
            txtResultat.setText("DIFERENTS");
        }
        
    }
    
     /**
     * Mostra el registre anterior
     * @param equip Dades de l'objecte equip a mostrar
     */
    private void mostrarEquip(Equip equip){
        if (equip!=null){
            txtIdEquip.setText(Integer.toString(equip.getEq_id()));
            txtNomEquip.setText(equip.getEq_nom());
            txtEstadi.setText(equip.getEstadi());
            txtPoblacio.setText(equip.getPoblacio());
            txtCodPostal.setText(equip.getCod_postal());
        }
    }
    
     /**
     * Activa o desactiva els botons en funció de si estem en el primer o darrer
     * registre
     * @param pucEnrere true si puc tirar enrere, false en cas contrari
     * @param pucEndavant true si puc tirar endavant, false en cas contrari
     */
    private void actualitzarBotons(boolean pucEnrere, boolean pucEndavant){
        /*Aquest mètode hauria d'activar o desactivar els botons
        en funció de si estem o no en el primer registre o l'últim*/
        btnPrimer.setEnabled(pucEnrere);
        btnAnterior.setEnabled(pucEnrere);
        btnSeguent.setEnabled(pucEndavant);
        btnUltim.setEnabled(pucEndavant);
    }

     /**
     * Recupera les dades del formulari i les carrega en un objecte Equip
     */
    private Equip recuperarEquip(){
        String NomEquip = txtNomEquip.getText();
        String Estadi = txtEstadi.getText();
        String Poblacio = txtPoblacio.getText();
        String CodPostal = txtCodPostal.getText();
        
        if(!"".equals(NomEquip) && !"".equals(Estadi) && !"".equals(Poblacio) && !"".equals(CodPostal)){
            
            Pattern p = Pattern.compile("\\b\\d{5}\\b");
            Matcher m = p.matcher(CodPostal);
            if(m.matches()){
                return new Equip(NomEquip,Estadi,Poblacio,CodPostal);

            }
            else{
            txtResultat.setText("FALLA CODI POSTAL");
            }
        }
        else{
        txtResultat.setText("FALLA INSERCIÓ");
        
        }
        return null;
    }
}